apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Le Planqué 2
  description: |
    Votre chef vous emmène une clé USB, un soir, lorsque êtes seul dans l'open-space.

    - _"Tu pourrais regarder cela stp ? N'en parle pas aux autres. J'ai besoin de tes retours rapidement."_
    - _"C'est quoi ?"_
    - _"Pose pas trop de questions... J'ai l'impression que Popa cache des choses, alors vérifie ça."_

    Ne sachant quoi trop faire de tout cela, vous vous exécutez...
    Alors, vous avez trouvé quelque chose d'anormal dans ce PDF ?

    Format du flag : `24HIUT{...}`
  attribution: "[PandatiX](https://github.com/pandatix)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Easy

  flags:
    - "24HIUT{P0P_3mB3d_INt0_PeeDIEF}"

  files:
    - dist/Systematic_review_Coca-Cola_can_effectively_dissolve_gastric_phytobezoars_as_a_first-line_treatment.pdf

  hints:
    - text: |
        Il est possible de cacher des objets dans un autre fichier (pdf par exemple...)
      cost: 50
    - text: |
        Il est possible de casser le mot de passe d'archives zip avec un dictionnaire bien connu
      cost: 50