apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Voyage, voyage
  description: |
    Un employé de PopaCola a publié une photo sur sa story Instagram accompagné de la légende suivante : "Petit séminaire d'entreprise avec les collègues. Visite de notre nouvelle plus grosse usine en perspective 😎!"
    En tant que spécialiste des renseignements et investigation numérique au sein de FreizhCola, votre mission est de mener l'enquête afin de trouver l'emplacement de cette nouvelle usine. Cette information serait d'une grande aide pour vos dirigeants afin de planifier la suite des opérations...

    Pour résoudre ce challenge, vous devrez trouver:
    - **les coordonnées (au millième près, c'est-à-dire 3 décimales après la virgule) du lieu de prise de la photo**.
    
    Format du flag : `24HIUT{01.234, 01.234}`
  attribution: "[hashp4](https://x.com/hashp4_)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Hard
  topics:
    - OSINT
    - GEOINT

  flags:
    - 24HIUT{51.122, 17.033}
    - 24HIUT{51.122,17.033}

  files:
    - dist/instagram_story_873972794739082.jpg

  hints:
    - id: hint-0
      text: |
        Premièrement, reduisez la zone de recherche. Pour cela, il est essentiel d'analyser les plaques d'immatriculation des véhicules. Vous devriez aboutir sur un pays, une région et une ville.
      cost: 50

    - id: hint-1
      text: |
        Maintenant, il vous faut extraire les éléments intéressants de l'image. Les lieux et points d'intérêts. Ils peuvent ensuite être transposés en "features" OpenStreetMap. Soyez précis. Vous pouvez vous aider du Wiki [OpenStreetMap Wiki - Map features](https://wiki.openstreetmap.org/wiki/Map_features).
      cost: 50
      requirements:
        - hint-0

    - id: hint-2
      text: |
        Utilisez Overpass Turbo pour interagir avec l'API d'OpenStreetMap et établir une corrélation entre les différentes features que vous avez extrait précédemment. Il peut être intéressant d'évaluer la distance (approximative) entre les éléments pour réduire les faux positifs.
      cost: 50
      requirements:
        - hint-1
