apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Shamir le chat
  description: |
    C'est pas vrai ! J'ai encore laissé la fenêtre et ce f\*\*tu chat a encore tout détruit...
    Je suis sûr que ce sont ces malheureux de la concurrence qui l'ont entraîné ! On dit que je suis fou mais c'est certain, c'est un espion !

    Bref maintenant je dois tout ranger, et il semblerait qu'il m'ait piqué une clé et mangé le bout d'une autre.
    Comment faire sans mes 5 clés ?? Peut-être que 4 me suffiront...

    Format du flag : 24HIUT{...}
  attribution: "[PandatiX](https://github.com/pandatix)"
  value: 500
  decay: 5
  minimum: 50
  function: logarithmic
  state: visible

  tags:
    - Medium

  flags:
    - 24HIUT{Pas besoin de tout avoir, seulement un minimum}

  files:
    - dist/keys.txt

  hints:
    - id: hint-0
      text: |
        Shamir est un nom particulier... Regardez bien "Shamir keys" sur Google !
        Dans tous les cas, seulement 4 clés sur 5 me suffisent. Peut-être que le nom de ce chat est finalement bien choisi !
      cost: 50

    - id: hint-1
      text: |
        Il manque 23 hexas dans la clé partielle, impossible de la retrouver par brute force, vous allez y passer des mois !
        Par contre, si on pad à la bonne taille de clé, on devrait pouvoir se passer d'une partie de l'information (#entropie).
      cost: 50
      requirements:
        - hint-0
