apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Beverage Bazaar
  description: |
    J'ai du mal à me repérer dans tout ces fichiers mais il doit bien y avoir un mot de passe quelque part...
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  decay: 5
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Easy
  topics:
    - pentest

  hints:
    - id: hint-0
      text: |
        Le serveur de fichier est peut être accessible sans identification.
      cost: 50

    - id: hint-1
      text: |
        Un des username doit être utilisable pour se connecter.
        Encore faut-il trouver le bon mot de passe.
      cost: 50
      requirements:
        - hint-0

    - id: hint-2
      text: |
        J'ai entendu dire que le mot de passe de mdupuis a été modifié pendant une réunion.
      cost: 50
      requirements:
        - hint-1

  mana_cost: 1
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/scenario
