apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: "Beverage Bazaar"
  description: |
    J'ai du mal à me répérer dans tout ces fichiers mais il doit bien y avoir un mot de passe quelque part...
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  state: "visible"

  tags:
    - "Easy"
  topics:
    - "pentest"
  hints:
    - text: "Le serveur de fichier est peut être accessible sans identification."
      cost: 50
      id: "hint-0"
    - text: |
        Un des username doit être utilisable pour se connecter.
        Encore faut-il trouver le bon mot de passe.
      cost: 50
      id: "hint-1"
      requirements:
        - "hint-0"
    - text: |
        J'ai entendu dire que le mot de passe de mdupuis a été modifié pendant une réunion.
      cost: 50
      id: "hint-2"
      requirements:
        - "hint-1"
  decay: 5
  minimum: 100
  function: "logarithmic"
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: "/path/to/directory"
  destroy_on_flag: false
  shared: false
  mana_cost: 10
  timeout: 3600
  until: "2025-12-31T23:59:59Z"