apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Fatal Request
  description: |
    On y est presque !
    Le compte administrateur de cette machine doit renfermer un secret.

    Utiliser le compte de mdupuis pour vous connecter en SSH -> mdupuis:SecureShell@PopaCoola
    Format du flag : 24HIUT{FLAG}
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  decay: 5
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Medium
  topics:
    - pentest

  hints:
    - id: hint-0
      text: |
        Un de vos collègue a repéré une tâche planifiée sur la machine.
        Vous devriez regarder les permissions avec lesquelles elle s'exécute, ça vous donnera une idée pour la suite.
      cost: 50

    - id: hint-1
      text: |
        Message de Marc à Franck : 
        Il faudra que l'on pense à enlever les permissions sur la bibliothèque Python du script avant de le mettre en production.
      cost: 50
      requirements:
        - hint-0

    - id: hint-2
      text: |
        Il doit bien y avoir un moyen d'ajouter un bout de code malveillant dans le script Python pour qu'il s'exécute à chaque fois que l'on l'appelle.
      cost: 50
      requirements:
        - hint-1

  requirements:
    behavior: anonymized
    prerequisites:
      - pentest/beverage-bazaar

  mana_cost: 1
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/kubernetes.ExposedMonopod
    spec:
      domain: 24hiut2025.ctfer.io
      image: pentest/fatal-request:v0.1.0
      port: 22
      exposeType: NodePort
    outputs:
      connectionInfo: ssh -p {{ .Port }} {{ .Host }}
