apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: "Fatal Request"
  description: |
    On y est presque !
    Le compte administrateur de cette machine doit renfermer un secret.
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  state: "visible"
  requirements:
    behavior: "anonymized"
    prerequisites:
      - "pentest/beverage-bazaar"
  tags:
    - "Medium"
  topics:
    - "pentest"

  hints:
    - text: |
        Un de vos collègue a repéré une tâche planifiée sur la machine.
        Vous devriez regarder les permissions avec lesquelles elle s'exécute, ça vous donnera une idée pour la suite.
      cost: 50
      id: "hint-0"
    - text: |
        Message de Marc à Franck : 
        Il faudra que l'on pense à enlever les permissions sur la bibliothèque Python du script avant de le mettre en production.
      cost: 50
      id: "hint-1"
      requirements:
        - "hint-0"
    - text: |
        Il doit bien y avoir un moyen d'ajouter un bout de code malveillant dans le script Python pour qu'il s'exécute à chaque fois que l'on l'appelle.
      cost: 50
      id: "hint-2"
      requirements:
        - "hint-1"
  decay: 5
  minimum: 100
  function: "logarithmic"
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: "/path/to/directory"
  destroy_on_flag: false
  shared: false
  mana_cost: 10
  timeout: 3600
  until: "2025-12-31T23:59:59Z"