apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Sodastream
  description: |
    L'équipe d'analystes de Orangin-eau nous a transmis une capture réseau.
    Ils soupçonnent Popa Cola d'avoir compromis la machine de leur directeur.
    Aidez-les à mettre la main sur une preuve de cette compromission !

    Format du flag : `24HIUT{...}`
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Medium
  topics:
    - forensic
    - network

  files:
    - dist/sodastream-capture.pcapng

  flags:
    - text: 24HIUT{Us3_s3cur3_protocols}
