apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Memes 2/3
  description: |
    Visiblement, ce site pourrait bien vous rapporter des points pour la suite.
    L'un de vos objectifs est "d'enterrer Popa Cola", peut être y a-t-il quelque chose sous sa tombe ...

    Format du flag : `24HIUT{...}`
  attribution: "[FireFlans](https://github.com/FireFlans)"
  connection_info: "https://memes.24hiut25.ctfer.io"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Medium

  flags:
    - 24HIUT{3nTeRR0nS_P0p4_C0L4}

  hints:
    - id: hint-0
      text: Fouillez littéralement sous la tombe
      cost: 50

    - id: hint-1
      text: Une image peut en cacher une autre
      cost: 50
      requirements:
        - hint-0

    - id: hint-2
      text: "Les metadonnées, c'est comme son historique : ça se modifie"
      cost: 50
      requirements:
        - hint-1

  requirements:
    behavior: anonymized
    prerequisites:
      - misc/memes_1
