apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Ret2PopaCola
  description: |
    Notre équipe a trouvé un binaire appartenant à PopaCola.
    À première vue, il existe uniquement pour afficher les chiffres de ventes du jour...

    Une analyse approfondie semble nécessaire. Qui sait ce que vous pourriez y trouver.

    Format du flag : `24HIUT{...}`
  attribution: "[Souehda](https://github.com/Souehda)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Medium
  topics:
    - pwn

  flags:
    - 24HIUT{L3ts_K33p_Pwn1Ng_P0paC01a}

  files:
    - path: dist/
      mode: zip
      name: sources.zip

  hints:
    - id: hint-0
      text: |
        Connaissez-vous les [buffer overflow](https://beta.hackndo.com/buffer-overflow/) ?
      cost: 50

    - id: hint-1
      text: |
        Le nom du challenge vous indique de réaliser un [ret2win](https://ir0nstone.gitbook.io/notes/binexp/stack/ret2win). Courage !
      cost: 50
      requirements:
        - hint-0

  shared: true
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/scenario
    additional:
      # Keep connection info in additional (will be easier to migrate to a recipe later)
      connectionInfo: |
        {{- $hostport := index .Ports "4444/TCP" -}}
        {{- $parts := splitList ":" $hostport -}}
        {{- $host := index $parts 0 -}}
        {{- $port := "" -}}
        {{- if gt (len $parts) 1 -}}
          {{- $port = index $parts 1 -}}
        {{- end -}}
        nc {{ $host }} {{ $port }}
