apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Blog Cola 1/2
  description: |
    Popa Cola a récemment lancé un nouveau blog baptisé Blog Cola, dans le but de renforcer sa popularité auprès de la jeune génération.
    Malheureusement, ce site fait l'éloge de Popa Cola tout en critiquant ouvertement Freizh Cola, son principal concurrent - et votre employeur.

    Votre mission, en tant qu'agent loyal de Freizh Cola, est simple : infiltrer le site et accéder au panneau d'administration pour tenter de désactiver Blog Cola.
    
    Format du flag : 24HIUT{FLAG}
  attribution: "[Walbre](https://github.com/Walbre)"
  value: 500
  decay: 5
  minimum: 50
  function: logarithmic
  state: visible

  tags:
    - Easy
  topics:
    - web

  hints:
    - id: hint-0
      text: |
        Un admin semble passer sur le site à interval de temps régulier, il est peut être possible d'exploiter une XSS.
      cost: 50

  files:
    - path: dist/
      mode: zip
      name: sources.zip

  mana_cost: 1
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/deploy
    additional:
      # override default settings (used for Nginx local tests)
      ingressAnnotations: nil
      ingressNamespace: nil
      ingressLabels: nil
