apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Freizh Exam
  description: |
    Pour être sûr que vous soyez bien prêt à vous frotter à Popa Cola, nos équipes ont décidé de vous faire passer un challenge technique.
    Je suis sûr que ce sera une formalité pour vous !

    Format du flag : `24HIUT{...}`
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Easy
  topics:
    - reverse

  files:
    - dist/freizh-exam

  flags:
    - 24HIUT{plz_f0llow_CTFERIO_on_github}
