# yaml-language-server: $schema=../../../schema.json
apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: Blog Cola 2/2
  description: |
    Après avoir décovert la cyberattaque que vous avez mené contre leurs site, Popa Cola a décidé de faire une mise à jour de sécurité.
    
    Sera-t-elle assez robuste pour vous arreter ?
    
    Format du flag : 24HIUT{FLAG}
  attribution: "[Walbre](https://github.com/Walbre)"
  value: 500
  decay: 5
  minimum: 50
  function: logarithmic
  state: visible

  tags:
    - Medium
  topics:
    - web

  files:
    - path: dist/
      mode: zip
      name: sources.zip

  requirements:
    behavior: anonymized
    prerequisites:
      - web/blog_cola_1_2

  hints:
    - id: hint-0
      text: |
        Javascript permet plus de choses qu'un simple redirect. Il est peut-être possible d'utiliser fetch, car il transmet les cookies HttpOnly sur une same origin ?
      cost: 50

  mana_cost: 1
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/deploy
    additional:
      # override default settings (used for Nginx local tests)
      ingressAnnotations: nil
      ingressNamespace: nil
      ingressLabels: nil
