services:
  vulnerable-request:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctferio/fatal-request
    container_name: fatal-request
    ports:
      - "2200:22"
    restart: unless-stopped
