apiVersion: v1alpha1
kind: ctfer.io/Dynamic
spec:
  name: Layers
  description: |
    Hier soir, au bar local, vous avez payé quelques coups à des "collègues" de PopaCola.
    Ce qu'ils n'ont pas remarqué c'est qu'à force de se venter de leur nouvelle "création", vous avez entendu. D'ailleurs tout le bar l'a entendu... Ils en tiennent un **couche** eux alors...

    Chez FreizhCola, vous portez tout intérêt à la sécurité, même en dehors de vos horaires de travail ! C'est bien !
    Empli d'un fervent amour pour cette valeur, vous avez décidé de leur voler la clé USB qui contenait la dite création. OK c'est un peu discutable, mais tant pis pour eux...
    Pour des besoins de démo interne, il semblerait que ces andouilles l'aient stocké en tant qu'image Docker archivée.
    
    Trouvez comment accéder à ce nouveau système !
  attribution: "[PandatiX](https://github.com/pandatix)"
  value: 500
  decay: 5
  minimum: 50
  function: logarithmic
  state: visible

  tags:
    - Easy
    - Docker
  topics:
    - forensic
    - docker
    - dive

  files:
    - dist/authenticator.tar

  hints:
    - text: |
        Parfois, il n'est pas utile d'attaquer un problème de front : il suffit de regarder ce qu'il y a autour !
        Les images Docker sont composées en strates, ou _layers_. Regardez donc pas là...
      cost: 50
