apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: L'illusionniste 
  description: |
    Un magicien ne révèle jamais ses secrets, mais parfois les scripts révèlent plus qu'ils ne devraient.
    Quelque chose vous attend sur cette machine, caché derrière des couches d'automatisation.

    Les outils sont souvent plus puissants qu'ils n'y paraissent, et certains langages 
    peuvent faire bien plus que leur fonction première...

    Format du flag : `24HIUT{...}`
  attribution: "[Fr4gments](https://github.com/fr4gments)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Hard
    - Système

  hints:
    - id: hint-0
      text: |
        La légende raconte qu'un obscur grimoire, très apprécié des mages noirs,
        permettrait de détourner les binaires de leur usage premier.

        Si vous le trouvez, il pourrait bien vous aider à vous évader de cette prison…
        Peut-être est-il CACHÉ dans cette pièce ? Qui sait quel pouvoir vous détiendrez une fois dehors…

        HTAP$ ohce !
      cost: 50
    
    - id: hint-1
      text: |
        https://gtfobins.github.io/
      cost: 50
      requirements:
        - hint-0

  mana_cost: 1
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/scenario
    additional:
      # Keep connection info in additional (will be easier to migrate to a recipe later)
      connectionInfo: |
        {{- $hostport := index .Ports "22/TCP" -}}
        {{- $parts := splitList ":" $hostport -}}
        {{- $host := index $parts 0 -}}
        {{- $port := "" -}}
        {{- if gt (len $parts) 1 -}}
          {{- $port = index $parts 1 -}}
        {{- end -}}
        ssh -p {{ $port }} {{ $host }} user:password
