apiVersion: v1alpha1
kind: ctfer.io/DynamicIaC
spec:
  name: WordPressure
  description: |
    Nous avons trouvé un serveur web exposé de PopaCola !
    Essayez de trouver un moyen de vous connecter à l'interface d'administration pour voir ce qu'ils mijotent.

    Format du flag : `24HIUT{...}`
  attribution: "[WildPasta](https://github.com/WildPasta)"
  value: 500
  decay: 26
  minimum: 100
  function: logarithmic
  state: visible

  tags:
    - Medium

  topics:
    - web

  hints:
    - id: hint-0
      text: |
        Utilisez différents outils pour scanner les vulnérabilités de la technologie utilisée par le site web.
      cost: 50

    - id: hint-1
      text: |
        Est-ce que tous les plugins ont été mis à jours régulièrement ?
      cost: 50
      requirements:
        - hint-0

    - id: hint-2
      text: |
        Essayez d'exploiter la CVE-2024-10508
      cost: 50
      requirements:
        - hint-1

  mana_cost: 2
  timeout: 3600
  scenario:
    apiVersion: v1alpha1
    kind: sdk.ctfer.io/manual
    spec:
      directory: infra/scenario
